// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo6AOBfqQ4P9LAVoxx5SST_OqRm5Di2xs',
    appId: '1:30703188083:web:1ce3b0820e6e802df61206',
    messagingSenderId: '30703188083',
    projectId: 'us-project-36616',
    authDomain: 'us-project-36616.firebaseapp.com',
    storageBucket: 'us-project-36616.firebasestorage.app',
    measurementId: 'G-XTWRHQWB80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkQPLnAUYuj2TqXKo0BAfMOZcCoPLeWZQ',
    appId: '1:30703188083:android:1a37743c3d645dcaf61206',
    messagingSenderId: '30703188083',
    projectId: 'us-project-36616',
    storageBucket: 'us-project-36616.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChzIdC4irkVm-9pp1fpmaDWaE9NHocy6s',
    appId: '1:30703188083:ios:fad7a799b096b8c7f61206',
    messagingSenderId: '30703188083',
    projectId: 'us-project-36616',
    storageBucket: 'us-project-36616.firebasestorage.app',
    iosBundleId: 'com.example.semuria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChzIdC4irkVm-9pp1fpmaDWaE9NHocy6s',
    appId: '1:30703188083:ios:fad7a799b096b8c7f61206',
    messagingSenderId: '30703188083',
    projectId: 'us-project-36616',
    storageBucket: 'us-project-36616.firebasestorage.app',
    iosBundleId: 'com.example.semuria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo6AOBfqQ4P9LAVoxx5SST_OqRm5Di2xs',
    appId: '1:30703188083:web:89ff3bbadd890683f61206',
    messagingSenderId: '30703188083',
    projectId: 'us-project-36616',
    authDomain: 'us-project-36616.firebaseapp.com',
    storageBucket: 'us-project-36616.firebasestorage.app',
    measurementId: 'G-220N2996KV',
  );
}
